# Generated by Django 5.2.6 on 2025-09-18 04:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('resolution', models.CharField(choices=[('512x512', '512x512 (Basic)'), ('768x768', '768x768 (Standard)'), ('1024x1024', '1024x1024 (HD)'), ('1536x1536', '1536x1536 (Ultra HD)')], default='512x512', max_length=20)),
                ('num_inference_steps', models.IntegerField(default=50)),
                ('guidance_scale', models.FloatField(default=7.5)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('video_length', models.IntegerField(default=5, help_text='Video length in seconds')),
                ('fps', models.IntegerField(default=8, help_text='Frames per second')),
                ('output_url', models.URLField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('watermarked_url', models.URLField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('gpu_used', models.CharField(blank=True, max_length=100)),
                ('credits_used', models.IntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('likes_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPUNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('aws', 'AWS'), ('gcp', 'Google Cloud'), ('lambda_labs', 'Lambda Labs'), ('runpod', 'RunPod'), ('local', 'Local')], max_length=20)),
                ('gpu_type', models.CharField(max_length=100)),
                ('memory_gb', models.IntegerField()),
                ('endpoint_url', models.URLField()),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='available', max_length=20)),
                ('current_load', models.FloatField(default=0.0)),
                ('cost_per_hour', models.DecimalField(decimal_places=4, max_digits=10)),
                ('avg_processing_time', models.FloatField(blank=True, null=True)),
                ('total_generations', models.IntegerField(default=0)),
                ('uptime_percentage', models.FloatField(default=100.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_ping', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cost_per_hour', '-memory_gb'],
            },
        ),
        migrations.CreateModel(
            name='InfluencerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('model_type', models.CharField(choices=[('realistic', 'Realistic'), ('anime', 'Anime'), ('artistic', 'Artistic'), ('pro_model', 'Professional Model'), ('custom', 'Custom Uploaded')], max_length=20)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-Binary')], max_length=20)),
                ('model_path', models.CharField(max_length=500)),
                ('preview_image', models.ImageField(upload_to='influencer_previews/')),
                ('sample_images', models.JSONField(default=list)),
                ('is_premium', models.BooleanField(default=False)),
                ('credit_cost_multiplier', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('total_generations', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('beauty', 'Beauty'), ('lifestyle', 'Lifestyle'), ('fitness', 'Fitness'), ('business', 'Business'), ('travel', 'Travel'), ('food', 'Food & Beverage'), ('tech', 'Technology'), ('automotive', 'Automotive'), ('other', 'Other')], max_length=20)),
                ('prompt_text', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('suggested_resolution', models.CharField(choices=[('512x512', '512x512 (Basic)'), ('768x768', '768x768 (Standard)'), ('1024x1024', '1024x1024 (HD)'), ('1536x1536', '1536x1536 (Ultra HD)')], default='1024x1024', max_length=20)),
                ('suggested_steps', models.IntegerField(default=50)),
                ('suggested_guidance', models.FloatField(default=7.5)),
                ('usage_count', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-usage_count', '-created_at'],
            },
        ),
    ]
