# Generated by Django 5.2.6 on 2025-09-18 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_generation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generationcomment',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_generation.generation'),
        ),
        migrations.AddField(
            model_name='generationcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generationlike',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_generation.generation'),
        ),
        migrations.AddField(
            model_name='generationlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generationrating',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_generation.generation'),
        ),
        migrations.AddField(
            model_name='generationrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='influencermodel',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generation',
            name='influencer_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_generation.influencermodel'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='generationlike',
            unique_together={('user', 'generation')},
        ),
        migrations.AlterUniqueTogether(
            name='generationrating',
            unique_together={('user', 'generation')},
        ),
    ]
