# Generated by Django 5.2.6 on 2025-09-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('subscription_created', 'Subscription Created'), ('subscription_cancelled', 'Subscription Cancelled'), ('credits_added', 'Credits Added'), ('credits_removed', 'Credits Removed'), ('model_approved', 'Influencer Model Approved'), ('model_rejected', 'Influencer Model Rejected'), ('content_moderated', 'Content Moderated'), ('payment_refunded', 'Payment Refunded'), ('promo_code_created', 'Promo Code Created'), ('system_setting_changed', 'System Setting Changed')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.CharField(blank=True, max_length=255)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('response_status', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('rate_limit_applied', models.BooleanField(default=False)),
                ('rate_limit_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentModerationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('generation', 'AI Generation'), ('comment', 'User Comment'), ('profile_image', 'Profile Image'), ('custom_model', 'Custom AI Model')], max_length=20)),
                ('content_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('reason_for_report', models.TextField()),
                ('moderator_notes', models.TextField(blank=True)),
                ('ai_safety_score', models.FloatField(blank=True, null=True)),
                ('ai_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('rollout_percentage', models.FloatField(default=0.0)),
                ('target_user_groups', models.JSONField(blank=True, default=list)),
                ('target_subscription_plans', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Information'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source_system', models.CharField(max_length=100)),
                ('source_component', models.CharField(blank=True, max_length=100)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('config_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], max_length=20)),
                ('description', models.TextField()),
                ('is_sensitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('users_total', 'Total Users'), ('users_active_daily', 'Daily Active Users'), ('users_active_monthly', 'Monthly Active Users'), ('revenue_daily', 'Daily Revenue'), ('revenue_monthly', 'Monthly Revenue'), ('generations_total', 'Total Generations'), ('generations_daily', 'Daily Generations'), ('gpu_utilization', 'GPU Utilization'), ('processing_time_avg', 'Average Processing Time'), ('subscription_churn', 'Subscription Churn Rate'), ('credit_burn_rate', 'Credit Burn Rate'), ('storage_used', 'Storage Used (GB)'), ('bandwidth_used', 'Bandwidth Used (GB)')], max_length=50)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'metric_type'],
            },
        ),
    ]
