# Generated by Django 5.2.6 on 2025-09-18 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditlog',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentmoderationqueue',
            name='content_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_moderated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentmoderationqueue',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentmoderationqueue',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='systemmetrics',
            unique_together={('metric_type', 'date')},
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['user', 'created_at'], name='admin_panel_user_id_f7aa48_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['endpoint', 'created_at'], name='admin_panel_endpoin_9786d7_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['ip_address', 'created_at'], name='admin_panel_ip_addr_903540_idx'),
        ),
    ]
